version: 2
updates:
  # Ruby (Bundler)
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly        # dailyだとPRが多すぎる場合はweekly推奨
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(bundler)"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(actions)"

  # npm（sass / bootstrap など）
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(npm)"
    # メジャー更新をまとめたい/一旦避けたい場合の例（任意）
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
