services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.prod
      secrets:
        - rails_master_key
        - db_url
    env_file: .env                      # ← EC2 に作った .env を利用
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      RAILS_ENV: "production"
      RACK_ENV:  "production"
      RAILS_MASTER_KEY_FILE: /run/secrets/rails_master_key
      RAILS_SERVE_STATIC_FILES: "1"
      RAILS_LOG_TO_STDOUT: "1"
      AWS_REGION: "ap-southeast-2"
      AWS_S3_BUCKET: "dolcos-calc-prod-assets"
    secrets:
      - rails_master_key
    command: bash -lc "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    restart: unless-stopped
    volumes:
      - ./config/credentials/production.key:/app/config/credentials/production.key:ro

secrets:
  rails_master_key:
    file: ./config/credentials/production.key
  db_url:
    environment: DATABASE_URL
