default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL",
          "postgres://postgres:postgres@db:5432/dolcos_calc_development"
        ) %>

test:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL",
          "postgres://postgres:postgres@db:5432/dolcos_calc_test"
        ) %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") {
          "postgres://#{ENV.fetch('POSTGRES_USER','postgres')}:#{ENV.fetch('POSTGRES_PASSWORD','postgres')}@db:5432/#{ENV.fetch('POSTGRES_DB','dolcos_calc_production')}"
        } %>
