default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL",
          "postgres://postgres:postgres@db:5432/dolcos_calc_development"
        ) %>

test:
  <<: *default
  url: <%= ENV.fetch(
          "DATABASE_URL",
          "postgres://postgres:postgres@db:5432/dolcos_calc_test"
        ) %>

production:
  <<: *default
  # 本番はRDSのみに固定。フォールバック無しで fail-fast
  url: <%= ENV.fetch("DATABASE_URL") %>
  # rds.force_ssl=1 を有効にする場合の書き方（どちらか一方）
  # variables:
  #   sslmode: "require"
